# En la sección de imports, cambia esto:
from config.queries import *

# Por esto:
from config.queries import (
    QUERY_OBTENER_MIEMBROS,
    QUERY_BUSCAR_MIEMBRO,
    QUERY_INSERTAR_MIEMBRO,
    QUERY_OBTENER_MIEMBRO_POR_ID,
    QUERY_OBTENER_APORTES_MIEMBRO,
    QUERY_OBTENER_TOTAL_APORTES_MES,
    QUERY_OBTENER_PRESTAMOS_MIEMBRO,
    QUERY_OBTENER_PRESTAMOS_ACTIVOS,
    QUERY_OBTENER_MULTAS_MIEMBRO,
    QUERY_OBTENER_MULTAS_PENDIENTES,
    QUERY_OBTENER_HISTORIAL_MIEMBRO
)
